stages:
- stage: 'DeployToDev'
  displayName: 'Deploy to the dev environment'
  dependsOn: DeployFunction
  condition: succeeded('DeployFunction')
  variables:
  - group: Release  
  jobs:
  - template: DeployWebApp.yml
    parameters:
      envName: 'dev'
      webAppName: '$(WebAppNameDev)'
      leaderboardAppName: '$(LeaderboardAppName)'