stages:
- stage: 'DeployToProduction'
  displayName: 'Deploy to the Production (pre-release slot)'
  dependsOn: DeployToStaging
  condition: succeeded('DeployToStaging')
  jobs: 
  - deployment: Deploy
    pool: 
      vmImage: 'ubuntu-16.04'
    environment: production
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy: 
          steps: 
          - download: current 
            artifact: drop 
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs: 
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(WebAppNameProduction)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/Tailspin.SpaceGame.Web.zip' 
              resourceGroupName: '$(ResourceGroupName)'
              deployToSlotOrASE: 'true'
              slotName: '$(WebAppNameProductionRC1Slot)'
          - task: AzureAppServiceSettings@1
            displayName: 'Update web app settings'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: $(WebAppNameProduction)
              slotName: '$(WebAppNameProductionRC1Slot)'
              resourceGroupName: $(ResourceGroupName)
              appSettings: |
                [
                  {
                    "name": "AppSettings:LeaderboardFunctionUrl",
                    "value": "http://$(LeaderboardAppName).azurewebsites.net/api/LeaderboardFunction",
                    "slotSetting": true
                  }
                ]
