stages:
- stage: 'DeployToTest'
  displayName: 'Deploy to the test environment'
  dependsOn: DeployToDev
  condition: succeeded('DeployToDev')
  # condition: eq(variables['Build.Reason'], 'Schedule')
  variables:
  - group: Release
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(WebAppNameTest)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/Tailspin.SpaceGame.Web.zip'
          - task: AzureAppServiceSettings@1
            displayName: 'Update web app settings'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: $(WebAppNameTest)
              resourceGroupName: $(ResourceGroupName)
              appSettings: |
                [
                  {
                    "name": "AppSettings:LeaderboardFunctionUrl",
                    "value": "http://$(LeaderboardAppName).azurewebsites.net/api/LeaderboardFunction",
                    "slotSetting": false
                  }
                ]
  - job: RunUITests
    displayName: 'Run UI tests'
    dependsOn: Deploy
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '$(System.DefaultWorkingDirectory)/**/*UITests.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Run UI tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration)'
        projects: '$(System.DefaultWorkingDirectory)/**/*UITests.csproj'
        publishTestResults: true
        testRunTitle: 'UI Tests'
