parameters: 
- name: envName
  default: 'dev'
- name: webAppName
  default: ''
  type: string
- name: leaderboardAppName
  default: ''
  type: string
  
jobs:
- deployment: DeployWebApp
  pool:
    vmImage: 'ubuntu-16.04'
  environment: ${{ parameters.envName }}
  variables:
  - group: Release
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: '$(azureServiceConnection)'
            appName: ${{ parameters.webAppName }}
            package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/Tailspin.SpaceGame.Web.zip'
        - task: AzureAppServiceSettings@1
          displayName: 'Update web app settings'
          inputs:
            azureSubscription: '$(azureServiceConnection)'
            appName: ${{ parameters.webAppName }}
            resourceGroupName: $(ResourceGroupName)
            appSettings: |
              [
                {
                  "name": "AppSettings:LeaderboardFunctionUrl",
                  "value": "http://${{ parameters.leaderboardAppName }}.azurewebsites.net/api/LeaderboardFunction",
                  "slotSetting": false
                }
              ]
