stages:
- stage: 'DeployToStaging'
  displayName: 'Deploy to the staging environment'
  dependsOn: DeployToTest
  condition: succeeded('DeployToTest')
  variables:
  - group: Release
  jobs:
  - template: DeployWebApp.yml
    parameters: 
      envName: 'staging'
      webAppName: '$(WebAppNameStaging)'
      leaderboardAppName: '$(LeaderboardAppName)'
  - template: RunLoadTests.yml
