stages:
- stage: 'DeployToTest'
  displayName: 'Deploy to the test environment'
  dependsOn: DeployToDev
  condition: succeeded('DeployToDev')
  # condition: eq(variables['Build.Reason'], 'Schedule')
  variables:
  - group: Release
  jobs:
  - template: DeployWebApp.yml
    parameters: 
      envName: 'test'
      webAppName: '$(WebAppNameTest)'
      leaderboardAppName: '$(LeaderboardAppName)'
  - template: RunUITests.yml
