trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    exclude:
    - experiments/*
  paths:
    exclude:
    - README.md
    - LICENSE*

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.100'
  azureServiceConnection: 'LSG-Tailspin-SpaceGame'
  
stages:
- template: Tailspin.SpaceGame.Deploy/Build.yml
- template: Tailspin.SpaceGame.Deploy/DBAVerificationScript.yml
- template: Tailspin.SpaceGame.Deploy/DBAVerificationApply.yml
- template: Tailspin.SpaceGame.Deploy/DeployFunction.yml
  parameters:
    envName: 'spike'
    functionName: '$(LeaderboardAppName)'
- template: Tailspin.SpaceGame.Deploy/DeployToDev.yml
- template: Tailspin.SpaceGame.Deploy/DeployToTest.yml
- template: Tailspin.SpaceGame.Deploy/DeployToStaging.yml
- template: Tailspin.SpaceGame.Deploy/DeployToProduction.yml
